export const weighingForm = () => [
  {
    name: 'lastParto',
    label: 'Último pesaje',
    type: 'date',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'iec',
    label: 'Peso',
    type: 'input',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'lastPalpation',
    label: 'Gr./Día',
    type: 'date',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'state',
    label: 'C.Corp',
    type: 'select',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'observation',
    label: 'Estado',
    type: 'select',
    rows: 6,
    required: true,
    size: { sm: 6, xs: 12 },
  },
  {
    name: 'datePreñez',
    label: 'Alzada',
    type: 'input',
    required: true,
    size: { sm: 6, xs: 12 },
  },
]
