export const ROUTES_DICT = {
  register: "/register",
  login: "/login",
  dashboard: "/dashboard",
  sale: "/dashboard/colectiva-ventas",
  weight: "/dashboard/colectiva-pesaje",
  zeal: "/dashboard/colectiva-celos",
  service: "/dashboard/servicios",
  birth: "/dashboard/nacimientos",
  palpations: "/dashboard/palpaciones",
  emailVerified: "/email-verified/:userId",
  pregnancies: "/dashboard/preñeces",
  animalDetail: "/dashboard/animal-detail",
  animalControl: "/dashboard/control-animal",
  recoverPassword: "/recover-password",
  setup: "/setup",
};
