export const ROUTES_SLUGS = {
  /**
   * common routes slugs
   */
  create: "create",
  update: "update",
  delete: "delete",
  /**
   * General routes slugs
   */
  register: "register",
  login: "login",
  emailVerified: "email-verified",
  recoverPassword: "recover-password",
  dashboard: "dashboard",
  geneticStock: "genetic-stock",
  semen: "semen",
  movements: "movements",
  embryo: "embryo",
  colective: "colective",
  sale: "colectiva-ventas",
  service: "service",
  weight: "colectiva-pesaje",
  zeal: "colectiva-celos",
  iamn: "I.A-M.N",
  embryoTransfer: "transfer-embryo",
  account: "cuenta",
  profile: "perfil",
  user: "usuario",
  palpations: "palpaciones",
  birth: "nacimientos",
  pregnancies: "preñeces",
  plan: "plan",
  hacienda: "hacienda",
  animalDetail: "detalles-animal",
  animalControl: "control-animal",
  pedigree: "pedigree",
  setup: "setup",
};

export const ROUTES_DICT = {
  root: "/",
  register: `/${ROUTES_SLUGS.register}`,
  login: `/${ROUTES_SLUGS.login}`,
  dashboard: `/${ROUTES_SLUGS.dashboard}`,
  geneticStock: {
    root: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}`,
    geneticType: {
      root: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType`,
      list: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/list`,
      create: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/list/${ROUTES_SLUGS.create}`,
      update: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/list/:_id/${ROUTES_SLUGS.update}`,
      delete: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/list/:_id/${ROUTES_SLUGS.delete}`,
    },
    movements: {
      root: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/${ROUTES_SLUGS.movements}`,
      list: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/${ROUTES_SLUGS.movements}/list`,
      create: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/${ROUTES_SLUGS.movements}/list/${ROUTES_SLUGS.create}`,
      update: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/${ROUTES_SLUGS.movements}/list/:_id/${ROUTES_SLUGS.update}`,
      delete: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.geneticStock}/:geneticType/${ROUTES_SLUGS.movements}/list/:_id/${ROUTES_SLUGS.delete}`,
    },
  },
  service: {
    root: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}`,
    list: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list`,
    createIAMN: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list/${ROUTES_SLUGS.create}IAMN/`,
    updateIAMN: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list/:_id/${ROUTES_SLUGS.update}IAMN/`,
    updateET: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list/:_id/${ROUTES_SLUGS.update}ET/`,
    createET: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list/${ROUTES_SLUGS.create}ET/`,
    delete: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/list/_:id/${ROUTES_SLUGS.delete}`,
  },

  iamnCreate: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/${ROUTES_SLUGS.iamn}/${ROUTES_SLUGS.create}`,
  iamnUpdate: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/${ROUTES_SLUGS.iamn}/:id/${ROUTES_SLUGS.update}`,
  embryoTransferCreate: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/${ROUTES_SLUGS.embryoTransfer}/${ROUTES_SLUGS.create}`,
  embryoTransferUpdate: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/${ROUTES_SLUGS.embryoTransfer}/:id/${ROUTES_SLUGS.update}`,
  serviceDelete: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.service}/:id/${ROUTES_SLUGS.delete}`,
  account: `/${ROUTES_SLUGS.account}`,
  profile: `/${ROUTES_SLUGS.profile}`,
  users: `/${ROUTES_SLUGS.user}`,
  plan: `/${ROUTES_SLUGS.plan}`,
  hacienda: `/${ROUTES_SLUGS.hacienda}`,
  sale: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.sale}`,
  weight: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.weight}`,
  zeal: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.zeal}`,
  birth: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.birth}`,
  palpations: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.palpations}`,
  emailVerified: `/${ROUTES_SLUGS.emailVerified}`,
  pregnancies: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.pregnancies}`,
  animalDetail: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.animalDetail}`,
  pedigree: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.animalDetail}/:animalId/${ROUTES_SLUGS.pedigree}`,
  animalControl: `/${ROUTES_SLUGS.dashboard}/${ROUTES_SLUGS.animalControl}`,
  recoverPassword: `/${ROUTES_SLUGS.recoverPassword}`,
  setup: `/${ROUTES_SLUGS.setup}`,
};
