export const birthForm = () => [
  {
    name: 'id',
    label: 'Nro. de partos',
    type: 'input',
    required: true,
    size: { sm: 6, xs: 12 },
  },
  {
    name: 'crias',
    label: 'Crias',
    type: 'input',
    required: true,
    size: { sm: 6, xs: 12 },
  },
  {
    name: 'lastBirth',
    label: 'Último parto',
    type: 'date',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'iept',
    label: 'IEPT',
    type: 'input',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'iepu',
    label: 'IEPu',
    type: 'input',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'lastAbort',
    label: 'Último Aborto',
    type: 'date',
    required: true,
    size: { sm: 3, xs: 12 },
  },
  {
    name: 'comment',
    label: 'Comentario',
    type: 'multiline',
    rows: 4,
    required: true,
    size: { xs: 12 },
  },
]
