export const birthForm = () => [
  {
    name: 'lastParto',
    label: 'Último celo',
    type: 'date',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'iec',
    label: 'I.E.C',
    type: 'input',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'lastPalpation',
    label: 'Última palpación',
    type: 'date',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'state',
    label: 'Estado',
    type: 'select',
    required: true,
    size: { sm: 6, xs: 12 },
  },
  {
    name: 'observation',
    label: 'Observación',
    type: 'multiline',
    rows: 4,
    required: true,
    size: { xs: 12 },
  },
  {
    name: 'datePreñez',
    label: 'Fecha preñez',
    type: 'date',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'dayPreñez',
    label: 'Días preñéz',
    type: 'input',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'parto',
    label: 'Parto esperado',
    type: 'date',
    required: true,
    size: { sm: 4, xs: 12 },
  },
  {
    name: 'comment',
    label: 'Comentario',
    type: 'multiline',
    rows: 4,
    required: true,
    size: { xs: 12 },
  },
]
